version: '3.3'
services:
  db:
    image: postgres:15.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    build: ../frontend
    volumes:
      - ../frontend:/app/result_build/

  backend:
    build: ../backend/foodgram
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      # - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ${PWD}/../frontend/build:/usr/share/nginx/html/
      # - ${PWD}/../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value: