# Generated by Django 3.2.18 on 2023-04-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_recipeingredients_recipeingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeTags',
            new_name='RecipeTag',
        ),
    ]
