name: Django-app workflow

on:
  push:
    branches: [ main ]
    ...

jobs:
    # Запустить тестирование приложения
  tests:
    runs-on: ubuntu-latest
    steps:
    - ...
  # Собрать и отправить образ приложения на DockerHub
  build:
    runs-on: ubuntu-latest
    steps:
    - ...
  # Деплой приложения на удалённый сервер
  deploy:
    runs-on: ubuntu-latest
    needs: build # Не выполнять сразу, ждать, пока выполнится build
    steps:
    - ...